name: WireGuard VPN Test

on:
  push:
    branches: [ main ]

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check- Public IP
      run: |
        sudo apt update
        sudo apt install -y curl
        curl ifconfig.me > pulicip.txt
        echo "PUBLIC_IP=$(cat publicip.txt)" >> $GITHUB_ENV
        curl ifconfig.me
  
    - name: Install WireGuard
      run: |
        sudo apt update
        sudo apt install -y wireguard resolvconf sed

    - name: Run wg-easy container
      run: |
        curl https://raw.githubusercontent.com/hcica/wg-easy/refs/heads/master/docker-compose.yml -o docker-compose-template.yml
        cat docker-compose-template.yml | sed "s|<public_ip>|$PUBLIC_IP|g" > docker-compose.yml
        sudo docker compose up -d


    - name: Test wg-easy web UI port
      run: curl --fail $PUBLIC_IP:51821 || (echo "Web UI not responding")

    - name: Show running containers
      run: docker ps

    - name: Keep the job alive
      run: |
        echo "WireGuard is running. Keeping workflow alive..."
        while true; do
          sleep 60
          echo "Still running at $(date)..."
        done
